# add libcpr (HTTP Client) v1.11.1

SET(SSL_OPTION "CPR_FORCE_OPENSSL_BACKEND TRUE")
if(WIN32)
   SET(SSL_OPTION "CPR_FORCE_WINSSL_BACKEND TRUE")
elseif(APPLE)
   SET(SSL_OPTION "CPR_FORCE_DARWINSSL_BACKEND TRUE")
endif()

CPMAddPackage(
    NAME cpr
    URL    "https://github.com/libcpr/cpr/archive/refs/tags/1.11.1.tar.gz"
    VERSION 1.11.1
    DOWNLOAD_EXTRACT_TIMESTAMP TRUE
    OPTIONS "BUILD_SHARED_LIBS FALSE" "CURL_USE_LIBPSL OFF" "USE_LIBIDN2 OFF" ${SSL_OPTION}
) 
