# optional: download SFML 2.6.2

set(SFML_STATIC_LIBRARIES TRUE)

CPMAddPackage(
    NAME sfml
    URL    "https://github.com/SFML/SFML/archive/refs/tags/2.6.2.tar.gz"
    DOWNLOAD_EXTRACT_TIMESTAMP TRUE
    OPTIONS "BUILD_SHARED_LIBS FALSE" "SFML_USE_SYSTEM_DEPS FALSE" "SFML_BUILD_NETWORK FALSE" "SFML_BUILD_AUDIO FALSE"
) 
 