#ifndef APP_VERSION_HPP
#define APP_VERSION_HPP

// AUTO-GENERATED BY CMAKE, DO NOT EDIT!

// clang-format off
namespace chk {
  constexpr const char* APP_VERSION = "1.0.12";
}

#endif // APP_VERSION_HPP
// clang-format on
