#ifndef APP_VERSION_HPP
#define APP_VERSION_HPP

// AUTO-GENERATED BY CMAKE, DO NOT EDIT!

// clang-format off
namespace chk {
  constexpr const char* APP_VERSION = "2.0.1";
}

#endif // APP_VERSION_HPP
// clang-format on
